from typing import Protocol


class StorageBackend(Protocol):
    async def save(self, relative_path: str, content: bytes) -> str: ...

    async def read(self, storage_path: str) -> bytes: ...

    async def exists(self, storage_path: str) -> bool: ...

    async def delete(self, storage_path: str) -> None: ...

    async def list_prefix(self, prefix: str) -> list[str]: ...

    async def delete_prefix(self, prefix: str) -> None: ...

    async def usage(self) -> int: ...
